### PR TITLE
multi-arch kube-conformance image for amd64/arm64

### PR DESCRIPTION
**Pull request by zhlhahaha**
Changed Dockerfile and Makefile to make kube-conformance
docker image support both amd64 and arm64

Signed-off-by: Howard Zhang <howard.zhang@arm.com>
Signed-off-by: Bin Lu <bin.lu@arm.com>

### CODE REVIEW

**Comment by zhlhahaha** [comment]
ping @timothysc @stevesloka @kensimon

**Comment by timothysc** [comment]
@zhlhahaha - This repo has been deprecated in favor for the upstream conformance container.  

@johnSchnake - we should archive this repo.

**Comment by zhlhahaha** [comment]
hi @timothysc,  has sonobuoy plugin been deprecated either? Or are there other ways to customize sonobuoy test? 
I just refer to the document in following url https://sonobuoy.io/docs/v0.15.2/plugins/.
Thanks for telling.

**Comment by johnSchnake** [comment]
Thanks for letting us know that the docs still pointed here.

I’ve wanted to update that section for some time, I’ll make sure I get to that today to clarify each plugin.

We are currently working on investigating a few other plugin opportunities but dont have any other that are officially supported.

However, any tool aimed at K8s can make a good plugin. I’ve made a few unofficial ones here just for my own testing: https://github.com/johnSchnake/sonobuoy-plugins which you might find helpful to use or as inspiration for your own plugin.

**Comment by zhlhahaha** [comment]
Thanks for your answer @johnSchnake , I will refer new doc and your plugins to change my test.

**Pull request closed without merging**
